\glossarysection[\glossarytoctitle]{\glossarytitle}\glossarypreamble
\begin{theglossary}\glossaryheader
\glsgroupheading{glsnumbers}\relax \glsresetentrylist %
\glossentry{n_list}{\glossaryentrynumbers{\relax 
		\setentrycounter[]{page}\glsnumberformat{ix}}}%
\glossentry{nz_list}{\glossaryentrynumbers{\relax 
		\setentrycounter[]{page}\glsnumberformat{ix}}}%
\glossentry{nat_nums}{\glossaryentrynumbers{\relax 
		\setentrycounter[]{page}\glsnumberformat{ix}}}%
\glossentry{natz_nums}{\glossaryentrynumbers{\relax 
		\setentrycounter[]{page}\glsnumberformat{ix}}}%
\glossentry{poly-sized}{\glossaryentrynumbers{\relax 
		\setentrycounter[]{page}\glsnumberformat{ix}}}%
\glossentry{not-index}{\glossaryentrynumbers{\relax 
		\setentrycounter[]{page}\glsnumberformat{ix}}}%
\glossentry{not-replace}{\glossaryentrynumbers{\relax 
		\setentrycounter[]{page}\glsnumberformat{ix}}}%
\glossentry{item-selection}{\glossaryentrynumbers{\relax 
		\setentrycounter[]{page}\glsnumberformat{ix}}}%
\glossentry{binary-set}{\glossaryentrynumbers{\relax 
		\setentrycounter[]{page}\glsnumberformat{ix}}}%
\glossentry{kleene-set}{\glossaryentrynumbers{\relax 
		\setentrycounter[]{page}\glsnumberformat{ix}\delimN 
		\setentrycounter[]{page}\glsnumberformat{25}}}%
\end{theglossary}\glossarypostamble
